# Generated by Django 4.2 on 2023-04-29 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='player_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='player_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tournament_images/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('participants', models.ManyToManyField(to='webapp.teamparticipant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='teamparticipant',
            name='tournament',
            field=models.ManyToManyField(to='webapp.teamtournament'),
        ),
        migrations.AddField(
            model_name='teamparticipant',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TeamMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveSmallIntegerField(default=0)),
                ('away_score', models.PositiveSmallIntegerField(default=0)),
                ('away_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='webapp.teamparticipant')),
                ('home_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='webapp.teamparticipant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.teamtournament')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tournament_images/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('participants', models.ManyToManyField(to='webapp.singleparticipant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='singleparticipant',
            name='tournament',
            field=models.ManyToManyField(to='webapp.singletournament'),
        ),
        migrations.AddField(
            model_name='singleparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SingleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveSmallIntegerField(default=0)),
                ('away_score', models.PositiveSmallIntegerField(default=0)),
                ('away_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='webapp.singleparticipant')),
                ('home_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='webapp.singleparticipant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.singletournament')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
