# Generated by Django 4.2 on 2023-04-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_singleparticipant_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleparticipant',
            name='tournament',
            field=models.ManyToManyField(blank=True, to='webapp.singletournament'),
        ),
        migrations.AlterField(
            model_name='singletournament',
            name='participants',
            field=models.ManyToManyField(blank=True, to='webapp.singleparticipant'),
        ),
        migrations.AlterField(
            model_name='teamtournament',
            name='participants',
            field=models.ManyToManyField(blank=True, to='webapp.teamparticipant'),
        ),
    ]
